package GUI;

import Algorithms.SortingAlgorithm;
import java.awt.BorderLayout;
import java.util.Hashtable;
import javax.swing.JLabel;
import javax.swing.JSlider;

/**
 *
 * @author robert
 */
public class AlgorithmParameterGUIframe extends javax.swing.JFrame
{
    private SortingAlgorithm sortingAlgorithm;
    
    /**
     * Creates new form AlgorithmParameterGUIframe
     */
    public void setAlgorithm(SortingAlgorithm algorithm)
    {
        sortingAlgorithm = algorithm;
    }

    public void setAmountOfFightersFound()
    {
        String amountOfFightersFound = sortingAlgorithm.getAmountOfFightersInCSV();
        fightersFoundText.setText(amountOfFightersFound);
    }
    
    public AlgorithmParameterGUIframe()
    {
        initComponents();
        //The setAlgorithm is only called until AFTER this(which is always first cuz its in the constructing) is done, 
        //So sortingAlgorithm is not an object yet, just an uninitiated variable!
        //setAmountOfFightersFound();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backToMenuButton = new javax.swing.JToggleButton();
        poolSizeTextBox = new javax.swing.JTextField();
        pouleSizeText = new javax.swing.JLabel();
        tier1FightersTextField = new javax.swing.JTextField();
        tier1FightersPoolLabel = new javax.swing.JLabel();
        schoolAmountLabel = new javax.swing.JLabel();
        schoolTextField = new javax.swing.JTextField();
        fightersFoundText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backToMenuButton.setText("Main menu");
        backToMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMenuButtonActionPerformed(evt);
            }
        });

        pouleSizeText.setText("Fighters per pool:");

        tier1FightersTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tier1FightersTextFieldActionPerformed(evt);
            }
        });

        tier1FightersPoolLabel.setText("Max. tier 1 fighters per pool:");

        schoolAmountLabel.setText("Max. fighters from same school per pool: ");

        schoolTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schoolTextFieldActionPerformed(evt);
            }
        });

        fightersFoundText.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backToMenuButton)
                .addGap(0, 317, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pouleSizeText)
                            .addComponent(tier1FightersPoolLabel))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tier1FightersTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(poolSizeTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(schoolAmountLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(schoolTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fightersFoundText))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backToMenuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fightersFoundText)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(poolSizeTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pouleSizeText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tier1FightersTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tier1FightersPoolLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(schoolAmountLabel)
                    .addComponent(schoolTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 172, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backToMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMenuButtonActionPerformed
        MainGUIframe mainGuiFrame = new MainGUIframe();
        this.setVisible(false);
        mainGuiFrame.setVisible(true);
    }//GEN-LAST:event_backToMenuButtonActionPerformed

    private void tier1FightersTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tier1FightersTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tier1FightersTextFieldActionPerformed

    private void schoolTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schoolTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_schoolTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(AlgorithmParameterGUIframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(AlgorithmParameterGUIframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(AlgorithmParameterGUIframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(AlgorithmParameterGUIframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new AlgorithmParameterGUIframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton backToMenuButton;
    private javax.swing.JLabel fightersFoundText;
    private javax.swing.JTextField poolSizeTextBox;
    private javax.swing.JLabel pouleSizeText;
    private javax.swing.JLabel schoolAmountLabel;
    private javax.swing.JTextField schoolTextField;
    private javax.swing.JLabel tier1FightersPoolLabel;
    private javax.swing.JTextField tier1FightersTextField;
    // End of variables declaration//GEN-END:variables
}
