package GUI;

import Algorithms.SortingAlgorithm;
import java.awt.BorderLayout;
import java.util.Hashtable;
import javax.swing.JLabel;
import javax.swing.JSlider;

/**
 *
 * @author robert
 */
public class AlgorithmParameterGUIframe extends javax.swing.JFrame
{
    private SortingAlgorithm sortingAlgorithm;
    
    /**
     * Creates new form AlgorithmParameterGUIframe
     */
    public void setAlgorithm(SortingAlgorithm algorithm)
    {
        sortingAlgorithm = algorithm;
    }
    
    private void initiateSliders()
    {
        JSlider schoolLevelSlider = new JSlider();
        JSlider skillLevelSlider = new JSlider();
        
        schoolLevelSlider.setBounds(10, 100, 180, 50);
        skillLevelSlider.setBounds(10, 160, 180, 50);
        
        this.add(schoolLevelSlider);
        this.add(skillLevelSlider);
        
        schoolLevelSlider.setVisible(true);
        skillLevelSlider.setVisible(true);
        
        schoolLevelSlider.setPaintTicks(true);
        skillLevelSlider.setPaintTicks(true);
        
        Hashtable labelTable = new Hashtable();
        labelTable.put(new Integer(25), new JLabel("25%"));
        labelTable.put(new Integer(50), new JLabel("50%"));
        labelTable.put(new Integer(75), new JLabel("75%"));
        
        schoolLevelSlider.setPaintLabels(true);
        skillLevelSlider.setPaintLabels(true);
        schoolLevelSlider.setSnapToTicks(true);
        skillLevelSlider.setSnapToTicks(true);
        
        schoolLevelSlider.setLabelTable(labelTable);
        skillLevelSlider.setLabelTable(labelTable);
    }
    
    public AlgorithmParameterGUIframe()
    {
        initComponents();
        initiateSliders();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backToMenuButton = new javax.swing.JToggleButton();
        poolSizeTextBox = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backToMenuButton.setText("Main menu");
        backToMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMenuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backToMenuButton)
                .addGap(0, 317, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(poolSizeTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backToMenuButton)
                .addGap(111, 111, 111)
                .addComponent(poolSizeTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 146, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backToMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMenuButtonActionPerformed
        MainGUIframe mainGuiFrame = new MainGUIframe();
        this.setVisible(false);
        mainGuiFrame.setVisible(true);
    }//GEN-LAST:event_backToMenuButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(AlgorithmParameterGUIframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(AlgorithmParameterGUIframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(AlgorithmParameterGUIframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(AlgorithmParameterGUIframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new AlgorithmParameterGUIframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton backToMenuButton;
    private javax.swing.JTextField poolSizeTextBox;
    // End of variables declaration//GEN-END:variables
}
