package GUI;

import Algorithms.SortingAlgorithm;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author robert
 */
public class AlgorithmParameterGUIframe extends javax.swing.JFrame
{
    private SortingAlgorithm sortingAlgorithm;
    
    /**
     * Creates new form AlgorithmParameterGUIframe
     */
    
    public AlgorithmParameterGUIframe()
    {
        initComponents();
    }
    
    public void setAlgorithm(SortingAlgorithm algorithm)
    {
        sortingAlgorithm = algorithm;
    }

    public void setAmountOfFightersFound()
    {
        String amountOfFightersFound = "Total amount of fighters: " + sortingAlgorithm.getTotalFightersAmount();
        fightersFoundText.setText(amountOfFightersFound);
    }   
    
    private boolean areParametersFilledIn()
    {
        ArrayList<JTextField> alltextFields = new ArrayList<JTextField>()
        {{ add(eliteSizeTextField); add(amountOfPoolsText); add(schoolMatesTextField); }};
        
        for(JTextField j : alltextFields)
        {
            if(j.getText() == null || j.getText().equals("") || !j.getText().matches("\\d+"))
            {
                System.out.println("areParametersFilledIn(): Parameters not or falsely filled in");
                return false;
            }
            else
            {
                return true;
            }  
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backToMenuButton = new javax.swing.JToggleButton();
        pouleSizeText = new javax.swing.JLabel();
        tier1FightersPoolLabel = new javax.swing.JLabel();
        schoolAmountLabel = new javax.swing.JLabel();
        fightersFoundText = new javax.swing.JLabel();
        runButton = new javax.swing.JButton();
        amountOfPoolsText = new javax.swing.JTextField();
        eliteSizeTextField = new javax.swing.JTextField();
        schoolMatesTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backToMenuButton.setText("Main menu");
        backToMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMenuButtonActionPerformed(evt);
            }
        });

        pouleSizeText.setText("Amount of pools:");

        tier1FightersPoolLabel.setText("Max. tier 1 fighters per pool:");

        schoolAmountLabel.setText("Max. fighters from same school per pool: ");

        fightersFoundText.setText("jLabel1");

        runButton.setText("Run the algorithm!");
        runButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backToMenuButton)
                .addGap(0, 317, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pouleSizeText)
                            .addComponent(tier1FightersPoolLabel)
                            .addComponent(schoolAmountLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(amountOfPoolsText, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                            .addComponent(eliteSizeTextField)
                            .addComponent(schoolMatesTextField))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fightersFoundText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(runButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backToMenuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fightersFoundText)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pouleSizeText)
                    .addComponent(amountOfPoolsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tier1FightersPoolLabel)
                    .addComponent(eliteSizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(schoolAmountLabel)
                    .addComponent(schoolMatesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(runButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backToMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMenuButtonActionPerformed
        MainGUIframe mainGuiFrame = new MainGUIframe();
        this.setVisible(false);
        mainGuiFrame.setVisible(true);
    }//GEN-LAST:event_backToMenuButtonActionPerformed
   
    private void runButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runButtonActionPerformed
        if(areParametersFilledIn() == true)
        {
            int amountOfPools = Integer.parseInt(amountOfPoolsText.getText());
            int eliteFighters = Integer.parseInt(eliteSizeTextField.getText());
            int schoolMates = Integer.parseInt(schoolMatesTextField.getText());
            sortingAlgorithm.setAlgorithmParameters(amountOfPools, eliteFighters, schoolMates);
            sortingAlgorithm.runAlgorithm();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please fill in all parameters.");
        }
    }//GEN-LAST:event_runButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(AlgorithmParameterGUIframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(AlgorithmParameterGUIframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(AlgorithmParameterGUIframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(AlgorithmParameterGUIframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new AlgorithmParameterGUIframe().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountOfPoolsText;
    private javax.swing.JToggleButton backToMenuButton;
    private javax.swing.JTextField eliteSizeTextField;
    private javax.swing.JLabel fightersFoundText;
    private javax.swing.JLabel pouleSizeText;
    private javax.swing.JButton runButton;
    private javax.swing.JLabel schoolAmountLabel;
    private javax.swing.JTextField schoolMatesTextField;
    private javax.swing.JLabel tier1FightersPoolLabel;
    // End of variables declaration//GEN-END:variables
}
