/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import FileChoosing.csvFileHandler;
import java.awt.Component;
import java.awt.event.WindowEvent;
import java.io.File;
import java.util.ArrayList;
import javax.swing.*;

/**
 *
 * @author robert
 */
public class MainGUIframe extends javax.swing.JFrame {
    
    /**
     * Creates new form MainGUIframe
     */
    public MainGUIframe() {
        initComponents();
        FileChooser.setVisible(false);
    }
    
    private int showFileChooser()
    {
        FileChooser.setVisible(true);
        int returnVal = FileChooser.showOpenDialog(null);
        System.out.println(returnVal);
        return returnVal;
    }
    
    private ArrayList<String> getGivenCsvRowNames()
    {
        ArrayList<String> returnList = new ArrayList<String>();
        //ugly duplication, need to fix this
        returnList.add('"' + FighterNameInput.getText() + '"');
        returnList.add('"' + FighterSkillInput.getText() + '"');
        returnList.add('"' + FighterSchoolInput.getText() + '"');
        return returnList;
    }
    
    private boolean allTextFieldsAreFilledIn()
    {
        ArrayList<String> textFieldContents = getGivenCsvRowNames();
        
        for(String textFieldValue : textFieldContents)
        {
            if(textFieldValue.equals(""))
            {
                JOptionPane.showMessageDialog(null, "Please fill in all the required fields.");
                return false;
            }
        }
        return true;
    }
     
    private csvFileHandler createCsvFileInstance()
    {
        csvFileHandler givenCsvFile = new csvFileHandler();
        return givenCsvFile;
    }
    
    private boolean fileIsSelectedByUser(int fileChooserValue)
    {
        if(fileChooserValue == FileChooser.APPROVE_OPTION)
            return true;
        else
            return false;
    }
    
    private void sendSelectedFileToCsvFileInstance(csvFileHandler csvFileInstance)
    {
        int returnVal = showFileChooser();
        File file = FileChooser.getSelectedFile();
        csvFileInstance.setSelectedFile(file);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        FileChooser = new javax.swing.JFileChooser();
        FighterSkillLevel = new javax.swing.JPanel();
        ChooseFileText = new javax.swing.JLabel();
        ChooseFileButton = new javax.swing.JButton();
        chooseRowNamesText = new javax.swing.JLabel();
        FighterNameLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        FighterSchoolLevel = new javax.swing.JLabel();
        FighterSkillInput = new javax.swing.JTextField();
        FighterNameInput = new javax.swing.JTextField();
        FighterSchoolInput = new javax.swing.JTextField();

        FileChooser.setDialogTitle("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FighterSkillLevel.setName("EntryPanel"); // NOI18N

        ChooseFileText.setText("Here you can upload a .CSV file containing you fighters' data.");

        ChooseFileButton.setText("Upload");
        ChooseFileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChooseFileButtonMouseClicked(evt);
            }
        });
        ChooseFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseFileButtonActionPerformed(evt);
            }
        });

        chooseRowNamesText.setText("Please specify which columns in the CSV file contain the following information:");

        FighterNameLabel.setText("Fighter name:");

        jLabel2.setText("Fighter skill level:");

        FighterSchoolLevel.setText("Fighter school:");

        FighterNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FighterNameInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FighterSkillLevelLayout = new javax.swing.GroupLayout(FighterSkillLevel);
        FighterSkillLevel.setLayout(FighterSkillLevelLayout);
        FighterSkillLevelLayout.setHorizontalGroup(
            FighterSkillLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FighterSkillLevelLayout.createSequentialGroup()
                .addGroup(FighterSkillLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FighterSkillLevelLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(FighterSkillLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chooseRowNamesText, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                            .addGroup(FighterSkillLevelLayout.createSequentialGroup()
                                .addGroup(FighterSkillLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ChooseFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(FighterSkillLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, FighterSkillLevelLayout.createSequentialGroup()
                                            .addComponent(FighterNameLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(FighterNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, FighterSkillLevelLayout.createSequentialGroup()
                                            .addGroup(FighterSkillLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(FighterSkillLevelLayout.createSequentialGroup()
                                                    .addComponent(jLabel2)
                                                    .addGap(18, 18, 18))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FighterSkillLevelLayout.createSequentialGroup()
                                                    .addComponent(FighterSchoolLevel)
                                                    .addGap(29, 29, 29)))
                                            .addGroup(FighterSkillLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(FighterSchoolInput, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(FighterSkillInput, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(FighterSkillLevelLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(ChooseFileText, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        FighterSkillLevelLayout.setVerticalGroup(
            FighterSkillLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FighterSkillLevelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(ChooseFileText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chooseRowNamesText)
                .addGap(18, 18, 18)
                .addGroup(FighterSkillLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FighterNameLabel)
                    .addComponent(FighterNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FighterSkillLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(FighterSkillInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(FighterSkillLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FighterSchoolLevel)
                    .addComponent(FighterSchoolInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ChooseFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FighterSkillLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FighterSkillLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChooseFileButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChooseFileButtonMouseClicked
       if(allTextFieldsAreFilledIn())
       {
           int fileChooserReturnValue = showFileChooser(); 
           csvFileHandler csv = createCsvFileInstance();
           
           if(fileIsSelectedByUser(fileChooserReturnValue))
           {
                sendSelectedFileToCsvFileInstance(csv);
                ArrayList<String> givenCsvRowNames = getGivenCsvRowNames();
                csv.setGivenHeaderColumnNames(givenCsvRowNames);
                csv.sendCsvFileToAlgorithm();
                this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
           }   
       }   
    }//GEN-LAST:event_ChooseFileButtonMouseClicked

    private void ChooseFileButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ChooseFileButtonActionPerformed
    {//GEN-HEADEREND:event_ChooseFileButtonActionPerformed
        
    }//GEN-LAST:event_ChooseFileButtonActionPerformed

    private void FighterNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FighterNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FighterNameInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUIframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUIframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUIframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUIframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUIframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChooseFileButton;
    private javax.swing.JLabel ChooseFileText;
    private javax.swing.JTextField FighterNameInput;
    private javax.swing.JLabel FighterNameLabel;
    private javax.swing.JTextField FighterSchoolInput;
    private javax.swing.JLabel FighterSchoolLevel;
    private javax.swing.JTextField FighterSkillInput;
    private javax.swing.JPanel FighterSkillLevel;
    private javax.swing.JFileChooser FileChooser;
    private javax.swing.JLabel chooseRowNamesText;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
